@startuml
hide empty members
skinparam linetype polyline
skinparam arrowLollipopColor #ADD1B2

MainView -right(0- MainPresenter : IMainContract.Presenter
MainView -right0)- MainPresenter : IMainContract.View
MainPresenter -right(0- GasolinerasRepository : IGasolinerasRepository
MainView -left..-> InfoView : <<use>>
MainView -left..-> DetailsView : <<use>>
MainView -down..-> FiltrosView : <<use>>
MainView -down..-> CombustibleView : <<use>>
MainView -up..-> PaymentHistoryView : <<use>>
MainView -up..-> RegisterPaymentView: <<use>>
MainView -up..-> DiscountListView: <<use>>
MainView -up..-> RegisterDiscountView: <<use>>


FiltrosView -right(0- FiltrosPresenter: IFiltrosContract.Presenter
FiltrosView -right0)- FiltrosPresenter : IFiltrosContract.View

CombustibleView -right(0- CombustiblePresenter: ICombustibleContract.Presenter
CombustibleView -right0)- CombustiblePresenter : ICombustibleContract.View
CombustiblePresenter -right(0- GasolinerasRepository : IGasolinerasRepository


PaymentHistoryView -right(0- PaymentHistoryPresenter: IPaymentHistoryContract.Presenter
PaymentHistoryView-right0)- PaymentHistoryPresenter : IPaymentHistoryContract.View
PaymentHistoryPresenter -right(0- LibreriaRoom: IPagoDAO 

RegisterPaymentView-right(0- RegisterPaymentPresenter: IRegisterPaymentContract.Presenter
RegisterPaymentView-right0)- RegisterPaymentPresenter : IRegisterPaymentContract.View

DiscountListView-right(0- DiscountListPresenter: IRegisterPaymentContract.Presenter
DiscountListView-right0)- DiscountListPresenter: IRegisterPaymentContract.View
DiscountListPresenter -right(0- LibreriaRoom: IDescuentoDAO 

RegisterDiscountView-right(0- RegisterDiscountPresenter: IRegisterDiscountContract.Presenter
RegisterDiscountView-right0)- RegisterDiscountPresenter: IRegisterDiscountContract.View



interface ICombustileContract#Presenter {
    + init(View view, TipoCombustible tipoCombustible)
    + onStationClicked(Gasolinera station)
    + onMenuInfoClicked()
    + onMenuHistoryClicked()
    + onMenuFiltrosClicked()
    + onMenuDescuentosClicked()
}

interface ICombustileContract#View {
    + init()
    + getGasolinerasRepository()
    + showStations(List<Gasolinera> stations)
    + showLoadCorrect(int stations)
    + showLoadError()
    + showStationDetails(Gasolinera station)
    + showInfoActivity()
    + showHistoryActivity()
    + showFiltrosActivity()
    + showDescuentosActivity()
}

interface IDiscountListCOntract#Presenter {
    + init(View view)
}

interface IDiscountListCOntract#View {
    + init()
    + getDescuentoDAO()
    + showDescuentos(List<Descuento> descuentos)
    + showErrorBD()
}

interface IFiltrosContract#Presenter {
    + init(View view)
    + onButtonConfirmarClick()
    + seleccionarFiltros()
    + seleccionarFiltrosOrden()
    + seleccionarFiltrosTipoCOmbustible()
}

interface IFiltrosContract#View {
    + lanzarBusquedaConFiltros()
    + opcionesIniciales()
}

interface IMainContract#Presenter {
    + init(View view)
    + onStationClicked(Gasolinera station)
    + onMenuInfoClicked()
    + onMenuHistoryClicked()
    + onMenuFiltrosClicked()
    + onMenuDescuentosClicked()
}

interface IMainContract#View {
    + init()
    + getGasolinerasRepository() : IGasolinerasRepository
    + showStations(List<Gasolinera> stations)
    + showLoadCorrect(int stations)
    + showLoadError()
    + showStationDetails(Gasolinera station)
    + showInfoActivity()
    + showHistoryActivity()
    + howFiltrosActivity()
    + showDescuentosActivity()
}

interface IPaymentHistoryContract#Presenter {
    + init(View view)
    + onMenuBackArrowClick()
}

interface IPaymentHistoryContract#View {
    + init()
    + getPagoDAO()
    + showPagos(List<Pagos> pagos)
    + showMainActivity()
    + showErrorBD()
}

interface IRegisterDiscountContract#Presenter {
    + init(VIew view)
    + onRegisterDiscountClicked(Descuento descuento)
    + onCancelRegistryClicked()
    + hayCamposVacios(Descuento d)
}

interface IRegisterDiscountContract#View {
    + init()
    + showDiscountHIstory()
    + showAlertDialog(String message, String title)
    + getDescuentoDAO()
    + getContext()
    + showSuccesDialog()

}

interface IRegisterPaymentContract#Presneter {
    + init(View view)
    + onRegisterPaymentClicked(String tipoGasolina, String nombreGasolinera, String precioPorLitro, String cantidad)
    + onMenuBackArrowClick()
}

interface IRegisterPaymentContract#View {
    + init()
    + showRegisterHistory()
    + getPagoDAO()
    + showAlertDialog(String message, String title)
    + showSuccesDialog()
    + getContext()
}





interface IGasolinerasRepository {
    + requestGasolineras(ICallBack cb, String ccaa)
    + requestGasolinerasCombustible(ICallBack cb, String combustible)
}

interface ICallBack {
    + onSuccess(List<Gasolinera> gasolineras)
    + onFailure(Throwable e)
}

interface IPagoDAO {
    + getAll()
    + loadAllByIds(int[] pagosIds)
    + findByName(String stationName)
    + insertAll(Pago pagos)
    + delete(Pago pago)
    + vaciaBD()

}

interface IDescuentoDAO {
    + getAll()
    + loadAllByIds(int[] discountsIds)
    + findByName(String discountName)
    + insertAll(Descuento descunetos)
    + delete(Descuento descuento)
    + update(boolean activo, String nombre)
    + vaciaBD()
}

interface IGasolinerasAPI {
    + gasolineras(String ccaa)
    + gasolinerasCombustible(String ccaa, String combustible)
}

@enduml